# path_info
# root_path: /home/neil/leondelee/pointmatching/graph/
root_path: /home/liangwei/3D/graph/
data_path: data/
checkpoint_path: checkpoints/
log_path: logs/

# dataset info
K: 40
dataset: modelnet

#model
num_points: 1024
in_channels: 3
out_channels: 40
mid_channels: 1000

#num_points: 5
#in_channels: 3
#out_channels: 3
#mid_channels: 5

drop_prob1: 0.1
drop_prob2: 0.45

first_cheb_order: 4
second_cheb_order: 3

# train
mode: debug
max_epoch: 100
lr: 0.0006
weight_decay: 0
lr_step: 20
lr_decay: 0.5
eval_step: 1
batch_size: 28
gpu: 0
init_cheb_std: 0.05
init_linear_std: 0.05

# results
name: demo
checkpoint_name: _best.pth
log_name: .log

