# path_info
root_path: /home/neil/leondelee/pointmatching/PointGCN/
# root_path: /home/liangwei/3D/graph/
data_path: /home/neil/leondelee/pointmatching/PointGCN/data/
checkpoint_path: checkpoints/
log_path: logs/

# dataset info
K: 10
dataset: modelnet

#model
num_points: 1024
in_channels: 3
out_channels: 10
mid_channels: 1000

#num_points: 5
#in_channels: 3
#out_channels: 3
#mid_channels: 5

drop_prob: 0.5

# train
mode: debug
max_epoch: 100
lr: 0.001
weight_decay: 0
lr_step: 20
lr_decay: 0.5
eval_step: 1
batch_size: 1
gpu: 0
task: cls

# results
name: dgc
checkpoint_name: _best.pth
log_name: .log

